# Generated by Django 2.2.24 on 2021-09-28 16:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='demande',
            name='adresse',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='autre',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='demande',
            name='daira',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='nomPrenom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='numeroTel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='poids',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='demande',
            name='wilaya',
            field=models.CharField(default='', max_length=200),
        ),
    ]
