# Generated by Django 2.2.24 on 2021-09-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0002_auto_20210928_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='nomPrenom',
        ),
    ]
