# Generated by Django 2.2.24 on 2021-09-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0003_remove_demande_nomprenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='nomPrenom',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='ordonnance',
            field=models.CharField(choices=[('1', 'Oui'), ('2', 'Non')], default='1', max_length=200),
        ),
    ]
