# Generated by Django 2.2.24 on 2021-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0004_auto_20210928_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='endroit',
            field=models.CharField(choices=[('1', 'Maison'), ('2', 'Hopital')], default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='maladieChronique',
            field=models.CharField(choices=[('1', 'Oui'), ('2', 'Non')], default='1', max_length=200),
        ),
        migrations.AddField(
            model_name='demande',
            name='oxygene',
            field=models.CharField(choices=[('1', '10-20'), ('2', '20-30'), ('3', '30-40'), ('4', '40-50')], default='8', max_length=200),
        ),
    ]
