# Generated by Django 2.2.24 on 2021-09-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0005_auto_20210928_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='oxygene',
            field=models.CharField(choices=[('1', '10-20'), ('2', '20-30'), ('3', '30-40'), ('4', '40-50'), ('5', '50-60'), ('6', '60-70')], default='8', max_length=200),
        ),
    ]
