# Generated by Django 2.2.24 on 2021-09-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0007_auto_20210928_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='daira',
        ),
        migrations.AddField(
            model_name='demande',
            name='commune',
            field=models.CharField(choices=[('1', 'Alger-Centre'), ('2', 'Sidi MHamed'), ('3', 'El Madania'), ('4', 'Belouizdad'), ('5', 'Bab El Oued'), ('6', 'Bologhine'), ('7', 'Casbah'), ('8', 'Oued Koriche'), ('9', 'Bir Mourad Raïs'), ('10', 'El Biar'), ('11', 'Bouzareah'), ('12', 'Birkhadem'), ('13', 'El Harrach'), ('14', 'Baraki'), ('15', 'Oued Smar'), ('16', 'Bachdjerrah'), ('17', 'Hussein Dey'), ('18', 'Kouba'), ('19', 'Bourouba'), ('20', 'Dar El Beïda'), ('21', 'Bab Ezzouar'), ('22', 'Ben Aknoun'), ('23', 'Dely Ibrahim'), ('24', 'El Hammamet'), ('25', 'Raïs Hamidou'), ('26', 'Djasr KasentinaNote 1'), ('27', 'El Mouradia'), ('28', 'Hydra'), ('29', 'Mohammadia'), ('30', 'Bordj El Kiffan'), ('31', 'El Magharia'), ('32', 'Beni Messous'), ('33', 'Les Eucalyptus'), ('34', 'Birtouta'), ('35', 'Tessala El Merdja'), ('36', 'Ouled Chebel'), ('37', 'Sidi Moussa'), ('38', 'Aïn Taya'), ('39', 'Bordj El Bahri'), ('40', 'El Marsa'), ('41', 'Hraoua'), ('42', 'Rouïba'), ('43', 'Reghaïa'), ('44', 'Aïn Benian'), ('45', 'Staoueli'), ('46', 'Zeralda'), ('47', 'Mahelma'), ('48', 'Rahmania'), ('49', 'Souidania'), ('50', 'Cheraga'), ('51', 'Ouled Fayet'), ('52', 'El Achour'), ('53', 'Draria'), ('54', 'Douera'), ('55', 'Baba Hassen'), ('56', 'Khraicia'), ('57', 'Saoula')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='demande',
            name='wilaya',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
