# Generated by Django 2.2.24 on 2021-09-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0008_auto_20210929_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='wilaya',
        ),
        migrations.AlterField(
            model_name='demande',
            name='maladieChronique',
            field=models.CharField(choices=[('1', 'Non'), ('2', 'Diabète'), ('2', 'hypertension artérielle'), ('3', 'Maladie pulmonaire chronique'), ('4', 'Cancer'), ('5', 'Syndrome de Down'), ('6', 'Maladie cardiovasculaire'), ('7', 'Enceinte'), ('8', 'Asthme'), ('9', 'Handicap'), ('10', 'Autre, Mentionné dans Autre')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='demande',
            name='ordonnance',
            field=models.CharField(choices=[('1', 'Oui, pour COVID'), ('2', 'Oui, pour une autre maladie pulmonaire'), ('2', 'Non')], default='1', max_length=200),
        ),
    ]
