# Generated by Django 2.2.24 on 2021-09-29 10:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0011_auto_20210929_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Age',
            field=models.IntegerField(default=0, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='adresse',
            field=models.CharField(default='', max_length=200, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='autre',
            field=models.TextField(default='', verbose_name='Autre'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='commune',
            field=models.CharField(choices=[('1', 'Alger-Centre'), ('2', 'Sidi MHamed'), ('3', 'El Madania'), ('4', 'Belouizdad'), ('5', 'Bab El Oued'), ('6', 'Bologhine'), ('7', 'Casbah'), ('8', 'Oued Koriche'), ('9', 'Bir Mourad Raïs'), ('10', 'El Biar'), ('11', 'Bouzareah'), ('12', 'Birkhadem'), ('13', 'El Harrach'), ('14', 'Baraki'), ('15', 'Oued Smar'), ('16', 'Bachdjerrah'), ('17', 'Hussein Dey'), ('18', 'Kouba'), ('19', 'Bourouba'), ('20', 'Dar El Beïda'), ('21', 'Bab Ezzouar'), ('22', 'Ben Aknoun'), ('23', 'Dely Ibrahim'), ('24', 'El Hammamet'), ('25', 'Raïs Hamidou'), ('26', 'Djasr KasentinaNote 1'), ('27', 'El Mouradia'), ('28', 'Hydra'), ('29', 'Mohammadia'), ('30', 'Bordj El Kiffan'), ('31', 'El Magharia'), ('32', 'Beni Messous'), ('33', 'Les Eucalyptus'), ('34', 'Birtouta'), ('35', 'Tessala El Merdja'), ('36', 'Ouled Chebel'), ('37', 'Sidi Moussa'), ('38', 'Aïn Taya'), ('39', 'Bordj El Bahri'), ('40', 'El Marsa'), ('41', 'Hraoua'), ('42', 'Rouïba'), ('43', 'Reghaïa'), ('44', 'Aïn Benian'), ('45', 'Staoueli'), ('46', 'Zeralda'), ('47', 'Mahelma'), ('48', 'Rahmania'), ('49', 'Souidania'), ('50', 'Cheraga'), ('51', 'Ouled Fayet'), ('52', 'El Achour'), ('53', 'Draria'), ('54', 'Douera'), ('55', 'Baba Hassen'), ('56', 'Khraicia'), ('57', 'Saoula')], default='1', max_length=200, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='endroit',
            field=models.CharField(choices=[('1', 'Maison'), ('2', 'Hopital')], default='1', max_length=200, verbose_name='Où se trouve le patient'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='maladieChronique',
            field=models.CharField(choices=[('1', 'Non'), ('2', 'Diabète'), ('2', 'hypertension artérielle'), ('3', 'Maladie pulmonaire chronique'), ('4', 'Cancer'), ('5', 'Syndrome de Down'), ('6', 'Maladie cardiovasculaire'), ('7', 'Enceinte'), ('8', 'Asthme'), ('9', 'Handicap'), ('10', 'Autre, Mentionné dans Autre')], default='1', max_length=200, verbose_name='Le patient souffre-t-il de maladies chroniques ?'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='nomPrenom',
            field=models.CharField(default='', max_length=200, verbose_name='Nom et prénom'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='numeroTel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='ordonnance',
            field=models.CharField(choices=[('1', 'Oui, pour COVID'), ('2', 'Oui, pour une autre maladie pulmonaire'), ('2', 'Non')], default='1', max_length=200, verbose_name='Avez-vous une ordonnance?'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='oxygene',
            field=models.CharField(choices=[('1', '10-20'), ('2', '20-30'), ('3', '30-40'), ('4', '40-50'), ('5', '50-60'), ('6', '60-70'), ('7', '70-80'), ('8', '80-90'), ('9', '90-100')], default='8', max_length=200, verbose_name="Pourcentage d'oxygène dans le sang"),
        ),
        migrations.AlterField(
            model_name='demande',
            name='poids',
            field=models.FloatField(default=0.0, verbose_name='Poids'),
        ),
    ]
