# Generated by Django 2.2.24 on 2021-09-29 17:25

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0012_auto_20210929_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='Age',
            field=models.IntegerField(default=0, verbose_name='العمر'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='adresse',
            field=models.CharField(default='', max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='autre',
            field=models.TextField(default='', verbose_name='ملاحظات أخرى'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='commune',
            field=models.CharField(choices=[(1, 'باب الواد'), (2, 'برج البحري'), (3, 'أولاد شبل'), (4, 'أولاد فايت'), (5, 'الأبيار'), (6, 'الجزائر الوسطى'), (7, 'الحامة - العناصر'), (8, 'الحراش'), (9, 'الحمامات'), (10, 'الدار البيضاء'), (11, 'الرايس حميدو'), (12, 'الرحمانية'), (13, 'الرغاية'), (14, 'الرويبة'), (15, 'السحاولة'), (16, 'السويدانية'), (17, 'الشراقة'), (18, 'العاشور'), (19, 'القبة'), (20, 'القصبة'), (21, 'الكاليتوس'), (22, 'المحالمة'), (23, 'المحمدية'), (24, 'المدنية'), (25, 'المرادية'), (26, 'المرسى'), (27, 'المقارية'), (28, 'بئر توتة'), (29, 'بئر خادم'), (30, 'بئر مراد رايس'), (31, 'باب الزوار'), (32, 'باب الواد'), (33, 'بابا حسن'), (34, 'باش جراح'), (35, 'براقي'), (36, 'برج البحري'), (37, 'برج الكيفان'), (38, 'بن عكنون'), (39, 'بني مسوس'), (40, 'بوروبة'), (41, 'بوزريعة'), (42, 'بولوغين'), (43, 'جسر قسنطينة'), (44, 'حسين داي'), (45, 'حيدرة'), (46, 'خرايسية'), (47, 'دالي إبراهيم'), (48, 'دويرة'), (49, 'زرالدة'), (50, 'سطاوالي'), (51, 'سيدي موسى'), (52, 'عين البنيان'), (53, 'عين طاية'), (54, 'هراوة'), (55, 'واد قريش'), (56, 'وادي السمار'), (57, 'بوزريعة'), (58, 'تسالة المرجة')], default='1', max_length=200, verbose_name='البلدية'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='endroit',
            field=models.CharField(choices=[('1', 'المنزل'), ('2', 'المستشفى')], default='1', max_length=200, verbose_name='مكان تواجد المريض'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='maladieChronique',
            field=models.CharField(choices=[('1', 'لا'), ('2', 'السكري'), ('3', 'ارتفاع ضغط الدم'), ('4', 'مرض رئوي مزمن'), ('5', 'السرطان'), ('6', 'متلازمة داون'), ('7', 'مرض القلب'), ('8', 'حامل'), ('9', 'الربو'), ('10', 'إعاقة'), ('11', 'مرض مزمن اخر, يذكر في الملاحظة')], default='1', max_length=200, verbose_name='هل لدى المريض أمراض مزمنة ؟'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='nomPrenom',
            field=models.CharField(default='', max_length=200, verbose_name='الإسم و اللقب'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='numeroTel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, unique=True, verbose_name='رقم هاتف مرافق المريض'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='ordonnance',
            field=models.CharField(choices=[('1', 'نعم, مرض كوفيد'), ('2', 'نعم, مرض رئوي اخر'), ('2', 'لا')], default='1', max_length=200, verbose_name='هل لديك وصفة ؟'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='oxygene',
            field=models.CharField(choices=[('1', '10-20'), ('2', '20-30'), ('3', '30-40'), ('4', '40-50'), ('5', '50-60'), ('6', '60-70'), ('7', '70-80'), ('8', '80-90'), ('9', '90-100')], default='8', max_length=200, verbose_name='نسبة الأكسجين في الدم'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='poids',
            field=models.FloatField(default=0.0, verbose_name='الوزن'),
        ),
    ]
