# Generated by Django 2.2.24 on 2021-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0014_auto_20210929_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='autre',
            field=models.CharField(default='', max_length=600, verbose_name='ملاحظات أخرى'),
        ),
    ]
