# Generated by Django 2.2.24 on 2021-09-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0018_auto_20210930_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concentrateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.FloatField(default=0.0, verbose_name='الحد الأقصى للتدفق')),
                ('pression', models.FloatField(default=0.0, verbose_name='ضغط المخرج')),
                ('electrique', models.FloatField(default=0.0, verbose_name='الكهرباء')),
                ('concentration', models.CharField(default='', max_length=200, verbose_name='تركيز الأكسجين')),
                ('sonore', models.FloatField(default=0.0, verbose_name='مستوى الصوت')),
                ('dimensions', models.CharField(default='', max_length=200, verbose_name='الأبعاد')),
                ('poids', models.FloatField(default=0.0, verbose_name='الوزن')),
                ('soupage', models.CharField(default='', max_length=200, verbose_name='صمام الإغاثة')),
            ],
        ),
        migrations.AlterField(
            model_name='demande',
            name='autre',
            field=models.TextField(blank=True, verbose_name='ملاحظات أخرى'),
        ),
    ]
