# Generated by Django 2.2.24 on 2021-09-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0019_auto_20210930_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concentrateur',
            name='debit',
        ),
        migrations.AddField(
            model_name='concentrateur',
            name='Debit',
            field=models.FloatField(default=0.0, verbose_name='LMP الحد الأقصى للتدفق'),
        ),
    ]
