# Generated by Django 2.2.24 on 2021-09-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0020_auto_20210930_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentrateur',
            name='Reference',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='الحد الأقصى للتدفق LMP'),
        ),
        migrations.AddField(
            model_name='concentrateur',
            name='autre',
            field=models.TextField(blank=True, verbose_name='ملاحظات أخرى'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='Debit',
            field=models.FloatField(default=0.0, verbose_name='الحد الأقصى للتدفق LMP'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='dimensions',
            field=models.CharField(default='', max_length=200, verbose_name='الأبعاد HxLxP'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='electrique',
            field=models.FloatField(default=0.0, verbose_name='الكهرباء HZ'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='poids',
            field=models.FloatField(default=0.0, verbose_name='الوزن KG'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='pression',
            field=models.FloatField(default=0.0, verbose_name='ضغط المخرج PSI'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='sonore',
            field=models.FloatField(default=0.0, verbose_name='مستوى الصوت DB'),
        ),
    ]
