# Generated by Django 2.2.24 on 2021-10-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0021_auto_20210930_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrateur',
            name='Reference',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='الرقم التسلسلي'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='dimensions',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='الأبعاد HxLxP'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='electrique',
            field=models.FloatField(blank=True, default=0.0, verbose_name='الكهرباء HZ'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='poids',
            field=models.FloatField(blank=True, default=0.0, verbose_name='الوزن KG'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='sonore',
            field=models.FloatField(blank=True, default=0.0, verbose_name='مستوى الصوت DB'),
        ),
        migrations.AlterField(
            model_name='concentrateur',
            name='soupage',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='صمام الإغاثة'),
        ),
    ]
