# Generated by Django 2.2.24 on 2021-10-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0024_demande_nci'),
    ]

    operations = [
        migrations.AddField(
            model_name='concentrateur',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='NCI',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='رقم بطاقة التعريف الوطنية'),
        ),
        migrations.AlterField(
            model_name='demandetraite',
            name='concentrateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concentrateursDemande.Concentrateur', verbose_name='الرقم التسلسلي'),
        ),
        migrations.AlterField(
            model_name='demandetraite',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concentrateursDemande.Demande', verbose_name='رقم بطاقة التعريف الوطنية'),
        ),
    ]
