# Generated by Django 2.2.24 on 2021-10-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0025_auto_20211002_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='traite',
            field=models.BooleanField(default=False, verbose_name='تم معالجة الطلب'),
        ),
    ]
