# Generated by Django 2.2.24 on 2021-10-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0026_demande_traite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concentrateur',
            name='disponible',
            field=models.CharField(choices=[('1', 'لا'), ('2', 'نعم')], default='2', max_length=10, verbose_name='متوفر'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='traite',
            field=models.BooleanField(choices=[('1', 'لا'), ('2', 'نعم')], default='1', max_length=10, verbose_name='تم معالجة الطلب'),
        ),
    ]
