# Generated by Django 2.2.24 on 2021-10-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0027_auto_20211002_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='traite',
            field=models.CharField(choices=[('1', 'لا'), ('2', 'نعم')], default='1', max_length=10, verbose_name='تم معالجة الطلب'),
        ),
    ]
