# Generated by Django 2.2.24 on 2021-10-06 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0029_auto_20211002_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='dateDemande',
            field=models.DateField(default=datetime.date(2021, 10, 6), verbose_name='تاريخ تسليم المكثف'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='numeroTel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+213', max_length=128, region='AG', unique=True, verbose_name='رقم هاتف مرافق المريض'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='ordonnance',
            field=models.CharField(choices=[('1', 'نعم, مرض كوفيد'), ('2', 'نعم, مرض رئوي اخر'), ('3', 'لا')], default='1', max_length=200, verbose_name='هل لديك وصفة ؟'),
        ),
        migrations.AlterField(
            model_name='demandetraite',
            name='concentrateur',
            field=models.ForeignKey(limit_choices_to={'disponible': '2'}, on_delete=django.db.models.deletion.CASCADE, to='concentrateursDemande.Concentrateur', verbose_name='الرقم التسلسلي'),
        ),
        migrations.AlterField(
            model_name='demandetraite',
            name='date',
            field=models.DateField(default=datetime.date(2021, 10, 6), verbose_name='تاريخ تسليم المكثف'),
        ),
        migrations.AlterField(
            model_name='demandetraite',
            name='demande',
            field=models.ForeignKey(limit_choices_to={'traite': '1'}, on_delete=django.db.models.deletion.CASCADE, to='concentrateursDemande.Demande', verbose_name='رقم بطاقة التعريف الوطنية'),
        ),
    ]
