# Generated by Django 2.2.24 on 2021-10-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0032_auto_20211013_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandetraite',
            name='dateRetour',
        ),
    ]
