# Generated by Django 2.2.24 on 2021-10-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0033_remove_demandetraite_dateretour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandetraite',
            old_name='dateEnvoie',
            new_name='date',
        ),
    ]
