# Generated by Django 2.2.24 on 2021-10-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0035_auto_20211013_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='dateDemande',
            field=models.DateField(default='2021-10-13', verbose_name='تاريخ تسليم المكثف'),
        ),
        migrations.AlterField(
            model_name='demandetraite',
            name='date',
            field=models.DateField(default='2021-10-13', verbose_name='تاريخ تسليم المكثف'),
        ),
    ]
