# Generated by Django 2.2.24 on 2021-10-13 22:53

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0039_auto_20211014_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='numeroTel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+213', max_length=128, region='AG', verbose_name='رقم هاتف مرافق المريض'),
        ),
    ]
