# Generated by Django 2.2.24 on 2021-10-17 08:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('concentrateursDemande', '0040_auto_20211014_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='NumMedecin',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+213', max_length=128, region='AG', verbose_name='رقم الطبيب المعالج'),
        ),
        migrations.AddField(
            model_name='demande',
            name='medecin',
            field=models.CharField(default='', max_length=200, verbose_name='إسم الطبيب المعالج'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='dateDemande',
            field=models.DateField(default='2021-10-17', verbose_name='تاريخ تسليم المكثف'),
        ),
        migrations.AlterField(
            model_name='demandetraite',
            name='date',
            field=models.DateField(default='2021-10-17', verbose_name='تاريخ تسليم المكثف'),
        ),
    ]
